# Generated by Django 2.2.9 on 2020-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200925_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionnotas',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
