# Generated by Django 2.2.9 on 2020-09-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200925_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionnotas',
            name='idAsignacion',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.AsignacionCursosUsuario'),
        ),
    ]
