from .user import UserSerializer, UserReadSerializer,UserSerializerCrearD
from .s_roles import RolesModelSerializer
from .s_cursos import CursosModelSerializer
from .s_cursosAsignacion import CursosAsignacionSerializer,CursosAsignacionadosSerializer
from .s_asignacionNotas import AsignacionNotasModelSerializer
